name: pico-friends

services:
  backend:
    build:
      context: ./spring-app
      dockerfile: Dockerfile
    container_name: pico-friends-api
    ports:
      - "7070:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - pico-friends

  frontend:
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile
    container_name: pico-friends-web
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://110.165.17.206:7070
    depends_on:
      - backend
    networks:
      - pico-friends

  redis:
    image: redis:7-alpine
    container_name: pico-friends-redis
    # ports:
    #   - "6379:6379"  # 외부 노출 제거 (네트워크 내부에서만 통신)
    command: docker-entrypoint.sh redis-server
    networks:
      - pico-friends

  storybook:
    build:
      context: ./storybook-app
      dockerfile: Dockerfile
    container_name: pico-friends-storybook
    ports:
      - "6006:80"
    networks:
      - pico-friends

volumes:
  redis-data:

networks:
  pico-friends:
    name: pico-friends
    driver: bridge
